/**
 * This package has lots of helper interfaces for frequently repeated methods
 */
package cn.nukkit.level.generator.populator.helper

import cn.nukkit.block.Block.fullId
import cn.nukkit.math.NukkitRandom.nextFloat
import cn.nukkit.math.MathHelper.sin
import cn.nukkit.math.MathHelper.cos
import cn.nukkit.math.NukkitRandom.nextBoundedInt
import cn.nukkit.math.NukkitRandom.nextDouble
import cn.nukkit.math.MathHelper.floor
import cn.nukkit.level.ChunkManager.getBlockIdAt
import cn.nukkit.level.ChunkManager.setBlockFullIdAt
import cn.nukkit.level.ChunkManager.setBlockAt
import cn.nukkit.block.Block.Companion.get
import cn.nukkit.math.Vector3.floorX
import cn.nukkit.math.Vector3.floorY
import cn.nukkit.math.Vector3.floorZ
import cn.nukkit.math.BlockVector3.y
import cn.nukkit.math.BlockVector3.x
import cn.nukkit.math.BlockVector3.z
import cn.nukkit.math.BlockVector3.setComponents
import cn.nukkit.math.BlockVector3.down
import cn.nukkit.math.BlockVector3.up
import cn.nukkit.math.BlockVector3.add
import cn.nukkit.math.BlockVector3.west
import cn.nukkit.math.BlockVector3.east
import cn.nukkit.math.BlockVector3.north
import cn.nukkit.math.BlockVector3.south
import cn.nukkit.math.BlockFace.getOpposite
import cn.nukkit.math.BlockFace.xOffset
import cn.nukkit.math.BlockFace.zOffset
import cn.nukkit.math.BlockFace.index
import cn.nukkit.math.Vector3.down
import cn.nukkit.math.Vector3.east
import cn.nukkit.math.Vector3.south
import cn.nukkit.math.BlockFace.Plane.random
import cn.nukkit.math.NukkitRandom.nextBoolean
import cn.nukkit.math.Vector3.setComponents
import cn.nukkit.math.Vector3.add
import cn.nukkit.math.Vector3.up
import cn.nukkit.math.Vector3.west
import cn.nukkit.math.Vector3.north
import cn.nukkit.block.Block.damage
import cn.nukkit.block.Block.id
import cn.nukkit.math.NukkitRandom.nextRange
import cn.nukkit.math.MathHelper.floor_double_long
import cn.nukkit.math.MathHelper.floor_float_int
import cn.nukkit.math.NukkitMath.randomRange
import cn.nukkit.level.format.FullChunk.getBlockId
import cn.nukkit.level.format.FullChunk.setBlock
import cn.nukkit.level.format.FullChunk.setBlockLight
import cn.nukkit.level.ChunkManager.getBlockDataAt
import cn.nukkit.level.ChunkManager.getChunk
import cn.nukkit.level.format.FullChunk.getBiomeId
import cn.nukkit.level.format.FullChunk.setFullBlockId
import cn.nukkit.level.format.FullChunk.setBlockId
import cn.nukkit.level.format.FullChunk.getHighestBlockAt
import cn.nukkit.level.format.FullChunk.getFullBlock
import kotlin.jvm.JvmOverloads
import cn.nukkit.block.BlockID
import cn.nukkit.level.ChunkManager
import cn.nukkit.math.NukkitRandom
import cn.nukkit.math.MathHelper
import cn.nukkit.level.generator.``object`
import cn.nukkit.block.BlockSapling
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.``object`
import cn.nukkit.block.BlockWood
import cn.nukkit.block.BlockLeaves
import cn.nukkit.math.Vector3
import cn.nukkit.math.BlockVector3
import cn.nukkit.math.BlockFace
import cn.nukkit.block.BlockUnknown
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.`object`.tree.ObjectDarkOakTree
import cn.nukkit.block.BlockWood2
import cn.nukkit.block.BlockLeaves2
import cn.nukkit.level.generator.`object`.tree.ObjectSavannaTree
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.`object`.mushroom.BigMushroom
import cn.nukkit.level.generator.noise.nukkit.d.NoiseD
import cn.nukkit.level.generator.noise.nukkit.d.PerlinD
import cn.nukkit.level.generator.noise.nukkit.d.SimplexD
import cn.nukkit.level.generator.noise.nukkit.f.NoiseF
import cn.nukkit.level.generator.noise.nukkit.f.PerlinF
import cn.nukkit.level.generator.noise.nukkit.f.SimplexF
import cn.nukkit.level.generator.noise.vanilla.d.NoiseGeneratorSimplexD
import cn.nukkit.level.generator.noise.vanilla.d.NoiseGeneratorImprovedD
import cn.nukkit.level.generator.noise.vanilla.f.NoiseGeneratorSimplexF
import cn.nukkit.level.generator.noise.vanilla.f.NoiseGeneratorImprovedF
import cn.nukkit.level.generator.populator.type.Populator
import cn.nukkit.level.format.FullChunk
import cn.nukkit.math.NukkitMath
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.populator.type.PopulatorCount
import cn.nukkit.level.generator.`object`.tree.ObjectTree
import cn.nukkit.level.biome.Biome
import cn.nukkit.level.biome.EnumBiome
import cn.nukkit.level.biome.type.CoveredBiome
import cn.nukkit.level.generator.populator.impl.PopulatorCaves
import cn.nukkit.level.generator.populator.type.PopulatorSurfaceBlock
import cn.nukkit.level.generator.populator.helper.PopulatorHelpers
import cn.nukkit.level.generator.populator.helper.EnsureCover
import cn.nukkit.level.generator.populator.helper.EnsureGrassBelow
import cn.nukkit.level.generator.populator.helper.EnsureBelow
import cn.nukkit.level.generator.populator.impl.PopulatorRavines
import cn.nukkit.level.generator.``object`
import cn.nukkit.level.generator.populator.impl.PopulatorGroundCover
import cn.nukkit.level.generator.Normal
import cn.nukkit.level.generator.populator.impl.PopulatorSugarcane
import it.unimi.dsi.fastutil.ints.IntSet
import it.unimi.dsi.fastutil.ints.IntOpenHashSet
